### ISSUE TITLE
GDPS Switch closes my game when updating to v1.1.2

### ISSUE THREAD

**Issue by XPAPlTA** [Kingminer7/gdps-switcher#10]
### Before making this report, check [known issues](https://github.com/Kingminer7/gdps-switcher/issues/5) and make sure there are no other reports about it.

**Describe the bug**
My game literally crashes when opening the game, like no popups, nothing, the game just closes

**To Reproduce**

**Expected behavior**
i'd see the gdps switch button and play the game normally

**Screenshots, videos, crashlogs**
None, just closes

**Platform you use**
Windows 11, 64 bits
**Additional context**
i just updated the gdps switcher to v1.1.2 and when i restarted, it closes the game out of nowhere, also i have 63 mods

**Comment by Kingminer7** [comment]
And there's no crashlogs?

**Comment by Foxiseminger** [comment]
no i tried

**Comment by Foxiseminger** [comment]
FOUND A FIX: Go to https://api.geode-sdk.org/v1/mods/km7dev.gdps-switcher/versions/1.1.1/download and it should download version 1.1.1 . After that, locate your GD directory and go to "gd dir\geode\mods\" and insert the .geode file you downloaded. After you done that, just open the game and no more errors.

**Comment by Foxiseminger** [comment]
if it says update the mod, do not it will break.

**Comment by Kingminer7** [comment]
@Foxiseminger Do you by chance have No Rate Limit

**Comment by FoxyWorld1** [comment]
yes I have nrl (btw fox's alt)

**Comment by Kingminer7** [comment]
yeah gdps switcher and no rate limit cause issues together, version 1.1.3 marks it as incompatible.
