### ISSUE TITLE
Crash when open online level or icon kit

### ISSUE THREAD

**Issue by Blip25** [Kingminer7/gdps-switcher#3]
When i open some of two, game crashes, but the custom servers works

**Comment by Kingminer7** [comment]
I'll check it out

**Comment by Kingminer7** [comment]
send a crashlog please

**Comment by Blip25** [comment]
> send a crashlog please

I don't now what are the expecific file , but here are all of that day installed the mod.
The los don't appear in geode , idk why
![Screenshot_20240701-105049_ZArchiver](https://github.com/Kingminer7/gdps-switcher/assets/130312651/6e57b55f-476a-4d28-8cee-ef08205b0b0a)
![Screenshot_20240701-105126_Geode](https://github.com/Kingminer7/gdps-switcher/assets/130312651/a624c8ce-06cc-43e8-9e22-6c8114cc38b1)

**Comment by Kingminer7** [comment]
are you able to attach the files to a message here

**Comment by Blip25** [comment]
> are you able to attach the files to a message here

sorry, i forget 😅
[Geode 2024-07-01 01.00.29.log](https://github.com/user-attachments/files/16058676/Geode.2024-07-01.01.00.29.log)
[Geode 2024-07-01 01.01.52.log](https://github.com/user-attachments/files/16058678/Geode.2024-07-01.01.01.52.log)
[Geode 2024-07-01 01.02.26.log](https://github.com/user-attachments/files/16058679/Geode.2024-07-01.01.02.26.log)
[Geode 2024-07-01 01.21.34.log](https://github.com/user-attachments/files/16058680/Geode.2024-07-01.01.21.34.log)
[Geode 2024-07-01 01.22.02.log](https://github.com/user-attachments/files/16058681/Geode.2024-07-01.01.22.02.log)
[Geode 2024-07-01 01.22.21.log](https://github.com/user-attachments/files/16058683/Geode.2024-07-01.01.22.21.log)
[Crash 2024-07-01 01.22.02.dmp](https://github.com/user-attachments/files/16058696/Crash.2024-07-01.01.22.02.dmp)
[Crash 2024-07-01 01.22.21.dmp](https://github.com/user-attachments/files/16058697/Crash.2024-07-01.01.22.21.dmp)
[Crash 2024-07-01 01.22.42.dmp](https://github.com/user-attachments/files/16058698/Crash.2024-07-01.01.22.42.dmp)
[Crash 2024-07-01 01.22.52.dmp](https://github.com/user-attachments/files/16058699/Crash.2024-07-01.01.22.52.dmp)
[Crash 2024-07-01 01.27.27.dmp](https://github.com/user-attachments/files/16058700/Crash.2024-07-01.01.27.27.dmp)

**Comment by Kingminer7** [comment]
> > are you able to attach the files to a message here
> 
> sorry, i forget 😅 [Geode 2024-07-01 01.00.29.log](https://github.com/user-attachments/files/16058676/Geode.2024-07-01.01.00.29.log) [Geode 2024-07-01 01.01.52.log](https://github.com/user-attachments/files/16058678/Geode.2024-07-01.01.01.52.log) [Geode 2024-07-01 01.02.26.log](https://github.com/user-attachments/files/16058679/Geode.2024-07-01.01.02.26.log) [Geode 2024-07-01 01.21.34.log](https://github.com/user-attachments/files/16058680/Geode.2024-07-01.01.21.34.log) [Geode 2024-07-01 01.22.02.log](https://github.com/user-attachments/files/16058681/Geode.2024-07-01.01.22.02.log) [Geode 2024-07-01 01.22.21.log](https://github.com/user-attachments/files/16058683/Geode.2024-07-01.01.22.21.log) [Crash 2024-07-01 01.22.02.dmp](https://github.com/user-attachments/files/16058696/Crash.2024-07-01.01.22.02.dmp) [Crash 2024-07-01 01.22.21.dmp](https://github.com/user-attachments/files/16058697/Crash.2024-07-01.01.22.21.dmp) [Crash 2024-07-01 01.22.42.dmp](https://github.com/user-attachments/files/16058698/Crash.2024-07-01.01.22.42.dmp) [Crash 2024-07-01 01.22.52.dmp](https://github.com/user-attachments/files/16058699/Crash.2024-07-01.01.22.52.dmp) [Crash 2024-07-01 01.27.27.dmp](https://github.com/user-attachments/files/16058700/Crash.2024-07-01.01.27.27.dmp)

Crash for online levels is an issue with projected stars, I already let the dev know and that should update soon.
I'm looking into the crash with the icon kit, seems to be related to Garage Plus

**Comment by Kingminer7** [comment]
Icon Kit crashing is a Garage Plus issue, I've made a pull request to that mod to fix the crash.
