### ISSUE TITLE
This mod is so broken

### ISSUE THREAD

**Issue by KrishTheNoob** [Kingminer7/gdps-switcher#4]
1: i can't log in or register using the other gdps
2: I CANNOT TURN OFF THE GDPS WTF BRO
3: why the fuck can't I play online levels 

https://github.com/Kingminer7/gdps-switcher/assets/172300545/4fdd31e9-49aa-4d28-b0f3-fa9760ce4d47

**Comment by Kingminer7** [comment]
Sorry, I was asleep
1. i'll check that out, worked for me before
2. robtop servers shoulda been automatically added, i'll have to make it pinned and check that its properly added
3. it seemed to work for me too, i'll check it again
