### ISSUE TITLE
[FEATURE REQUEST] Disabling Steam achievements

### ISSUE THREAD

**Issue by M336G** [Kingminer7/gdps-switcher#7]
### Before making this request, check [known issues](https://github.com/Kingminer7/gdps-switcher/issues/5) and make sure there are no other requests for it.

**Is your feature request related to a problem? Please describe.**
I'm pretty sure it is still possible to get achievements, e.g. the Geometry Star one if one of the levels you create get rated on the GDPS servers. I did not test this myself because I did not want to risk getting the achievement illegitimately.

**Describe the solution you'd like**
Simply disable achievements on Steam when you are on a different server.

**Describe alternatives you've considered**
Not launching Geometry Dash via Steam, which requires modifying the steam_api64.dll with an other one to be able to launch outside of Steam, and switch servers if the player wants to go back to playing on Steam to get their achievements on the normal servers before closing the game, which is very unpractical.

**Additional context**
Nothing much to say.

**Comment by Kingminer7** [comment]
good idea, I'll see what I can do about that

**Comment by Kingminer7** [comment]
unfortunately i do not see a way I could do this, i'm sorry
