### ISSUE TITLE
Doesn't work with fruitspace gdps's

### ISSUE THREAD

**Issue by aceinetx** [Kingminer7/gdps-switcher#8]
I got the server url from wireshark, put it in the gdps switcher, tried: nope. mod generates the server url perfectly fine, but it seems like it can't connect to it. the post parameters are exactly the same in both gd's. tried gdpsfh hosting - works fine. The gdps i'm trying to connect does support 2.2, so I have no idea what could be wrong

**To Reproduce**
Get a fruitspace gdps database url through wireshark
Remove the /database/*.php
Put in the gdps url
Refresh the levels page

**Expected behavior**
Successful connection to gdps

**Platform you use**
Windows

**Comment by Kingminer7** [comment]
> I got the server url from wireshark, put it in the gdps switcher, tried: nope. mod generates the server url perfectly fine, but it seems like it can't connect to it. the post parameters are exactly the same in both gd's. tried gdpsfh hosting - works fine. The gdps i'm trying to connect does support 2.2, so I have no idea what could be wrong
> 
> **To Reproduce** Get a fruitspace gdps database url through wireshark Remove the /database/*.php Put in the gdps url Refresh the levels page
> 
> **Expected behavior** Successful connection to gdps
> 
> **Platform you use** Windows

Try keeping /database/ - does it work?

**Comment by aceinetx** [comment]
No, tried everything: with /database/, without - nothing worked

**Comment by Kingminer7** [comment]
> No, tried everything: with /database/, without - nothing worked

In wireshark, do you receive any data from the servers, or is it just a 404 not found?

**Comment by aceinetx** [comment]
> > No, tried everything: with /database/, without - nothing worked
> 
> In wireshark, do you receive any data from the servers, or is it just a 404 not found?

nope, neither did I receive any http error or dns error. I tried to set filters to http.request.method == "POST" and it seems like it doesn't send a post request.

**Comment by Kingminer7** [comment]
> > > No, tried everything: with /database/, without - nothing worked
> > 
> > In wireshark, do you receive any data from the servers, or is it just a 404 not found?
> 
> nope, neither did I receive any http error or dns error. I tried to set filters to http.request.method == "POST" and it seems like it doesn't send a post request.

that's really strange
I know this seems kind of redundant but could you use the GDIntercept mod and see if it sees anything different to wireshark?

**Comment by aceinetx** [comment]
> > > > No, tried everything: with /database/, without - nothing worked
> > > 
> > > 
> > > In wireshark, do you receive any data from the servers, or is it just a 404 not found?
> > 
> > 
> > nope, neither did I receive any http error or dns error. I tried to set filters to http.request.method == "POST" and it seems like it doesn't send a post request.
> 
> that's really strange I know this seems kind of redundant but could you use the GDIntercept mod and see if it sees anything different to wireshark?

I tried GDIntercept now and it actually does see post requests, but the cloudflare http page says 404 not found. I have no idea why, i'm pretty sure wireshark wouldn't lie. I cannot use GDIntercept on gdps because it is on 2.204, but that would make resolving this problem mush easier

**Comment by Kingminer7** [comment]
> > > > > No, tried everything: with /database/, without - nothing worked
> > > > 
> > > > 
> > > > In wireshark, do you receive any data from the servers, or is it just a 404 not found?
> > > 
> > > 
> > > nope, neither did I receive any http error or dns error. I tried to set filters to http.request.method == "POST" and it seems like it doesn't send a post request.
> > 
> > 
> > that's really strange I know this seems kind of redundant but could you use the GDIntercept mod and see if it sees anything different to wireshark?
> 
> I tried GDIntercept now and it actually does see post requests, but the cloudflare http page says 404 not found. I have no idea why, i'm pretty sure wireshark wouldn't lie. I cannot use GDIntercept on gdps because it is on 2.204, but that would make resolving this problem mush easier

I'm honestly not sure, I'm sorry - only thing I can think of is somehow an incorrect url (which I doubt) or that the server only supports 2.204 and not 2.206 somehow.

**Comment by m41denx** [comment]
@aceinetx hello, FruitSpace owner here. Was just notified of this problem by one of gdps owners.
I'm currently unable to reproduce the issue. Could you provide server URL you're using and pcap dump if possible?
Also you need to specify URL in any of these formats:
```
http://rugd.gofruit.space/<gdps_id>/db/
https://rugd.gofruit.space/<gdps_id>/db/

gdps_id: ^[0-9A-Za-z]{4}$
Ex: https://rugd.gofruit.space/000S/db/
```

<details>
  <summary>Screenshots of 2.206 + GDPS Switcher working fine</summary>
<img width="1136" alt="Снимок экрана 2024-11-30 в 10 50 19" src="https://github.com/user-attachments/assets/d54194ed-1ea0-4eba-9557-5a360d91e0d6">
<img width="1136" alt="Снимок экрана 2024-11-30 в 10 50 59" src="https://github.com/user-attachments/assets/69d20b22-7968-4bba-aebe-7ceca49b4812">
<img width="1136" alt="Снимок экрана 2024-11-30 в 10 51 05" src="https://github.com/user-attachments/assets/2d2812f1-693f-415d-b983-6b842c3700be">
</details>

**Comment by aceinetx** [comment]
> ~~@aceinetx hello, FruitSpace owner here. Was just notified of this problem by one of gdps owners.~~
> ~~I'm currently unable to reproduce the issue. Could you provide server URL you're using and pcap dump if possible?~~
> ~~Also you need to specify URL in any of these formats:~~
> ```
> http://rugd.gofruit.space/<gdps_id>/db/
> https://rugd.gofruit.space/<gdps_id>/db/
> 
> gdps_id: ^[0-9A-Za-z]{4}$
> Ex: https://rugd.gofruit.space/000S/db/
> ```
> 
> <details>
>   <summary>Screenshots of 2.206 + GDPS Switcher working fine</summary>
> <img width="1136" alt="Снимок экрана 2024-11-30 в 10 50 19" src="https://github.com/user-attachments/assets/d54194ed-1ea0-4eba-9557-5a360d91e0d6">
> <img width="1136" alt="Снимок экрана 2024-11-30 в 10 50 59" src="https://github.com/user-attachments/assets/69d20b22-7968-4bba-aebe-7ceca49b4812">
> <img width="1136" alt="Снимок экрана 2024-11-30 в 10 51 05" src="https://github.com/user-attachments/assets/2d2812f1-693f-415d-b983-6b842c3700be">
> </details>
> 
> 
> **UPD: I can confirm 2.2074 doesn't work as intended**

То есть это все таки было багом? Я думал это я что то не понимаю, в ваершарке реквесты нормально отправлялись

**Comment by Kingminer7** [comment]
Fix released on mod index.
