### ISSUE TITLE
Server Removal VIA Mod Settings

### ISSUE THREAD

**Issue by Vaulto350** [Kingminer7/gdps-switcher#9]
The purpose of this enhancement is for when the mod crashes upon startup due to the server being selected doing weird stuff. (Namely, McGDPS)

Having this enhancement would allow being able to remove the faulty server while in Safe Mode.

Currently, the only fix is to delete the save data while in safe mode.

(Encountered on Android.)

**Comment by Kingminer7** [comment]
Do you have a crashlog?

**Comment by Vaulto350** [comment]
Not sure if I do.
